### ISSUE TITLE
Dependency (simple-markdown fork) not available in tagged versions

### ISSUE THREAD

**Issue by ExcellaCenter** [CharlesMangwa/react-native-simple-markdown#106]
All of the tagged versions of this library depend on git://github.com/CharlesMangwa/simple-markdown.git.  When I do an npm install, it is unable to pull in that library.  Have the permissions on the repo changed in some way?  Can the be changed back?

**Comment by ExcellaCenter** [comment]
Looks like it is something to do with NPM.  Perhaps a security feature.

**Comment by Devixx** [comment]
First start by doing this

delete node_modules folder
delete package-lock.json
delete yarn.lock

You can add this to your package.json as a workaround
`"resolutions": {
    "simple-markdown": "https://github.com/Khan/simple-markdown"
  },`

finally run npm/yarn install
