### ISSUE TITLE
Can't apply styles to links

### ISSUE THREAD

**Issue by Nekorsis** [CharlesMangwa/react-native-simple-markdown#11]
Hi, i have a markdown, looks something like this.
And the problem is. i can't apply different colours to link and text.
For example i want to set link colour to be red, and the rest of the text should be green. What would happen is only the first word of link would be red, the rest is green.
It seems like if links and text share same style rules, text styles override all the others.

My style object:

```
const markdownStyles = {
  plainText : {
    color: '#424242',
  },
  link : {
    color: '#03a9f4',
  },
}
```

My markdown :

```
lorem ipsum

[Link blah blah blah][1]

  [1]: https://github.com/
```

**Comment by neverlan** [comment]
Same problem for "strong" and "text" :)

**Comment by CharlesMangwa** [comment]
Hi @Nekorsis @neverlan! If I'm not mistaken guys: isn't because by default, MD doesn't accept color styling?

**Comment by CharlesMangwa** [comment]
Closing issue #11
