### ISSUE TITLE
Adding react-native-simple-markdown crashes android app

### ISSUE THREAD

**Issue by mswiszcz** [CharlesMangwa/react-native-simple-markdown#14]
Hey,

I wanted to use this library in my app, though when I try to add it to my component it causes app to crash on android. I am using React native 0.32.1 and testing the app on Nexus 5 device.

I dont have any stacktrace of what's going on and have no idea what may be wrong. What's weird is when I turn on Remote JS debug it works fine 😟

Other plugins I am using are:

```
    "react-native-linear-gradient": "^1.5.14",
    "react-native-router-flux": "^3.36.0",
    "react-native-simple-markdown": "^1.0.60-rc.2",
    "react-native-splash-screen": "^1.0.9"
```

**Comment by CharlesMangwa** [comment]
Hi @mswiszcz! How did you import/use it in you component plz? I didn't face this problem so far with my HTC 10 😕…

**Comment by mswiszcz** [comment]
I've imported everything exactly as in the Readme. Either way I've updated react-native to 0.36 and now the bug does **not** occur, I think we can close this issue :-)

**Comment by CharlesMangwa** [comment]
Perfect! Have fun 😁!

Closing issue #14
