### ISSUE TITLE
Text Color not working

### ISSUE THREAD

**Issue by HeinZawHtet** [CharlesMangwa/react-native-simple-markdown#18]
I try to apply color to Paragraph. but it's not working. Other types of properties works such as backgroundColor, fontSize....

**Comment by CharlesMangwa** [comment]
Hi @HeinZawHtet! If I'm not mistaken: Markdown doesn't support colors by default ([check this out](http://stackoverflow.com/questions/35465557/how-to-apply-color-in-markdown))… So this is probably a feature that need to implement by hand probably?

**Comment by mastermoo** [comment]
@HeinZawHtet apply color to Text, instead of Paragraph

**Comment by HeinZawHtet** [comment]
@mastermoo it's working. Thz you.

text : {
  color: "red",
}

**Comment by briancalvium** [comment]
We had a problem trying to have separate header colors from the base text color. Looking at the code, it seems like it *should* work, but no. Oddly, size seems to be OK.

**Comment by ammichael** [comment]
Guys, my styles are got working ☹️ 
```
const markdownStyles = {
  paragraph: {
    fontSize: 14,
    marginBottom: 10,
    lineHeight: 21,
  },
  text: {
	color: '#727272'
  }
}

<Markdown style={markdownStyles} key={Math.random()}>
    {content}
</Markdown>
```

Any ideas?

**Comment by formatlos** [comment]
seems like the text setting overwrites everything. setting the text-color explicitly to undefined did the trick for me `text: { color: undefined }`

**Comment by briancalvium** [comment]
Yes, we had issues with getting normal text to be one (non-default) color and headings/links to be another color. It seems leaving text have an undefined color and paragraph have the 'body text' color works, but I think the parser might need two newlines to detect it as a paragraph?

**Comment by jamesone** [comment]
How can you change the colour of other markdown such as **em** & **strong**? The same issue is occurring.

**Comment by jamesone** [comment]
@formatlos This did the trick!

**Comment by NawarYossef** [comment]
This issue is still occurring. any suggestions?

**Comment by quantumproducer** [comment]
```
export default class App extends React.Component {
  render() {
    return (
      <View style={styles.container}>
        <Text>Open up App.js to start working on your app!</Text>
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#ccc',
    color: '#ffffff',
    alignItems: 'center',
    justifyContent: 'center',
  },

  text: {
    color: "white"
  }
});
```

I see a grey background, black text.

**Comment by cesar-machado** [comment]
export default class App extends React.Component {
  render() {
    return (
      <View style={styles.container}>
        <Text style={styles.text}>Open up App.js to start working on your app!</Text>
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#ccc',
    alignItems: 'center',
    justifyContent: 'center',
  },

  text: {
    color: "#fff"
  }
});

this ways works.

**Comment by cesar-machado** [comment]
> export default class App extends React.Component {
>   render() {
>     return (
>       <View style={styles.container}>
>         <Text style={styles.text}>Open up App.js to start working on your app!</Text>
>       </View>
>     );
>   }
> }
> 
> const styles = StyleSheet.create({
>   container: {
>     flex: 1,
>     backgroundColor: '#ccc',
>     alignItems: 'center',
>     justifyContent: 'center',
>   },
> 
>   text: {
>     color: "#fff"
>   }
> });

react native accepts only in this way.

**Comment by cesar-machado** [comment]
export default class App extends React.Component {
  render() {
    return (
      <View style={styles.container}>
        <Text style={styles.text}>Open up App.js to start working on your app!</Text>
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#ccc',
    color: '#ffffff',
    alignItems: 'center',
    justifyContent: 'center',
  },

  text: {
    color: "#fff"
  }
});

react native accepts only in this way.

**Comment by cesar-machado** [comment]
`export default class App extends React.Component {
  render() {
    return (
      <View style={styles.container}>
        <Text>Open up App.js to start working on your app!</Text>
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#ccc',
    color: '#ffffff',
    alignItems: 'center',
    justifyContent: 'center',
  },

  text: {
    color: "white"
  }
});`
