### ISSUE TITLE
Unexpected view type nested under text node: class com.facebook.react.uimanager.LayoutShadowNode

### ISSUE THREAD

**Issue by afdalwahyu** [CharlesMangwa/react-native-simple-markdown#19]
I have problem with nested list.
for example my string is :
```
- Install it yourself from source code.
  -  Popular with developers who are familiar with Unix-like systems.
- Using third-party tools.
  - There are many third-party tools and package managers for installing Go, like apt-get in Ubuntu and homebrew for Mac.
```
does simple-markdown support nested?

**Comment by CharlesMangwa** [comment]
Hi @afdalwahyu! RNSM doesn't support nested list yet. As you saw, each item of the list referred to a `<Text />` component. But if you try to add a subitem, it's turned into a `<View />`, but RN doesn't allow to have a `<View />` component into a `<Text />`'s. I'll look into the matter asap, but every PR is welcome!

**Comment by undef1ned** [comment]
Any progress on that? :)

**Comment by CharlesMangwa** [comment]
Hi! I should handle this kind of issue with the new version coming soon

Closing issue #19

**Comment by alicelimacd** [comment]
Hi is this issue resolved in the version v1.0.60-rc.3?

**Comment by mattvot** [comment]
Can this be re-opened? Issue seems present in the latest version `1.0.60-rc.3`.

**Comment by arash-hacker** [comment]
i found my issue.  
this error happens when you want use button as text in react-navigation.  
my code was 
```
return {
      title: (
    <Button transparent onPress={() => navigation.goBack()}   >
      <Icon name="chat" />
    </Button>) ,
      headerLeft: (
        <Button transparent onPress={() => navigation.navigate("ScreenOne")}   >
          <Icon name="arrow-back" />
        </Button>),
      headerRight: (
        <Button transpar
```
so as u see i want use button as text so react-native-navigation think my header text is unsupported.  
using text in title **solved** my problem
