### ISSUE TITLE
App crashed if link title is bold style

### ISSUE THREAD

**Issue by bearpku** [CharlesMangwa/react-native-simple-markdown#21]
try this:
```
[__Google__](http://www.google.com)
```

**Comment by bearpku** [comment]
E/AndroidRuntime( 1763): com.facebook.react.uimanager.IllegalViewOperationException: Unexpected view type nested under text node: class com.facebook.react.uimana

**Comment by bearpku** [comment]
actually, it will crash even I put the the example in the readme:

      #Markdown in react-native is so cool!

      You can **emphasize** what you want, or just _suggest it_ 😏…

      You can even [link your website](http://charlesmangwa.surge.sh) or if you prefer: [email somebody](mailto:email@somebody.com)

      Spice it up with some GIF 💃:

      ![Some GIF](https://media.giphy.com/media/dkGhBWE3SyzXW/giphy.gif)

      And even add a cool video 😎!

      [![A cool video from YT](https://img.youtube.com/vi/dQw4w9WgXcQ/0.jpg)](http://www.youtube.com/watch?v=dQw4w9WgXcQ)

      [![Another one from Vimeo](https://i.vimeocdn.com/video/399486266_640.jpg)](https://vimeo.com/57580368)

**Comment by bearpku** [comment]
Actually I got what happened.
This package only support IOS. it won't work in Android.
Any plan to support Android?

**Comment by CharlesMangwa** [comment]
Hi @bearpku! This package does actually support both Android & iOS. Probably something went wrong during the last updates: I'll check it out this weekend!

**Comment by briancalvium** [comment]
I am using 1.0.60-rc.3, and this works in RN 0.38:
```
[**title**](http://www.google.com)
```

However, links are pretty hard to hit on android. I have made a custom rule for ```link``` with hitslop, but it doesn't seem to affect it. I would guess it's cut off by the parent bounds, but adding padding to the link style doesn't seem to work.

**Comment by CharlesMangwa** [comment]
@bearpku As @briancalvium mentioned, it will work if you use double ** ** to bold your title.

**Comment by CharlesMangwa** [comment]
Closing issue #21

**Comment by bearpku** [comment]
but it doesn't make sense to just support `** **` . Any plan to support `__ __` ?
