### ISSUE TITLE
Bullets in lists not aligned properly

### ISSUE THREAD

**Issue by afilp** [CharlesMangwa/react-native-simple-markdown#24]
I get these (non properly aligned) bullets, in Android:

![image](https://cloud.githubusercontent.com/assets/7850073/22368818/3c599f58-e491-11e6-8da6-a9edc841fdb3.png)

when using a list:

```
- Wi-Fi or Cable Fast Internet in the room\*
- PC Room rentals available\*
- 24 hour Reception
- 24 hour Security Patrols
- 24 hour Currency exchange
- Free shuttle service to Bufos beach 900m (3 times daily)
- Laundry service\*
```

**Comment by afilp** [comment]
@CharlesMangwa Any idea how this could be fixed? Thanks a lot!

**Comment by mrpatiwi** [comment]
+1

**Comment by CharlesMangwa** [comment]
Hi @afilp @mrpatiwi! Sorry for the late reply! You can set your own rules to customize this as you wish into `<Markdown />`'s style prop:

```js
  listItemBullet: {
    fontSize: 3,
    lineHeight: 2,
    marginTop: 1,
    anyOtherStyleProperty: 0,
  },
```

**Comment by afilp** [comment]
@CharlesMangwa Thanks Charles, 

This would require to know the font size of the Text after the bullet and if this changes the bullet lineHeight should also change, etc.

Wouldn't it be more appropriate to have a FLEX view around the two TEXT components, with ``flexDirection: 'row'`` and ``alignItems: 'center'``?

Something along these lines.

This should be done inside the library however, as this code could be added by the end user.

What do you think?

**Comment by af-inf** [comment]
@CharlesMangwa 
Would my proposition above be viable? 
(not sure if the internals of the library allow this)

Thanks again!

**Comment by CharlesMangwa** [comment]
Hi @afilp @af-inf! This could totally be viable, just need to implement it! I'm not satisfy with the actual API anymore. As you can see, each parsed element can just render a `Text`, or a `View` component. The idea with the next API is to be able to render nested component and customize them as you like. For instance: parse a specific text and render bullets points as `Touchable`'s. I just don't had enough time lately to work on it and implement all these features :/

**Comment by CharlesMangwa** [comment]
Fixed in https://github.com/CharlesMangwa/react-native-simple-markdown/commit/3b4147bd8729bb4875f0a2dbf2757e493d227cab
