### ISSUE TITLE
GIF's don't seem to render in Android. Using Version 0.40.0 of React Native.

### ISSUE THREAD

**Issue by jeffbonasso** [CharlesMangwa/react-native-simple-markdown#25]

**Comment by timzaak** [comment]
this needs to make react-native support gif. you can ref the document to find out how to make android react-native support gif.

**Comment by jeffbonasso** [comment]
Closer! I am getting some where. I don't know what document you are referring to be searching on web I found this...this gets the images to display but they aren't animating. Any more pointers? Is there a specific document I should be looking at?

By default the Gif images are not supported in android react native app. You need to set the following code to display the gif images. The code: Open your android/app/build.gradle file add the following code in the place of

open android/app/build.gradle add the following  code 

```
dependencies: { 
  ...
     // For animated GIF support
    compile 'com.facebook.fresco:animated-base-support:0.11.0'  
    // For WebP support, including animated WebP
    compile 'com.facebook.fresco:animated-gif:0.11.0'  
    compile 'com.facebook.fresco:animated-webp:0.11.0' 
    compile  'com.facebook.fresco:webpsupport:0.11.0'  
```

**Comment by CharlesMangwa** [comment]
Thanks a lot @jeffbonasso!

**Comment by Kernael** [comment]
I am also experiencing this issue, but no luck with this solution.

```
compile 'com.facebook.fresco:animated-base-support:1.0.1'
compile 'com.facebook.fresco:animated-gif:1.0.1'
compile 'com.facebook.fresco:animated-webp:1.0.1'
compile 'com.facebook.fresco:webpsupport:1.0.1'
```

Anyone also experiencing this again ?
