### ISSUE TITLE
Block level elements requiring two \n ?

### ISSUE THREAD

**Issue by robinschaaf** [CharlesMangwa/react-native-simple-markdown#26]
Hi - Apologies if this is obvious (and/or a weird implementation of MD) but I'm getting my MD from an API which I don't control, and  the block level elements (Heading, HR, etc) are only separated by one \n, whereas it appears that this implementation of it requires two \n.  (I believe they're using CommonMark)
For example, I get data like:
`# Heading1 #\n## Heading2 ##\n### Heading3 ###\n`

But to display properly using RNSM it appears to only work if it's
`# Heading1 #\n\n## Heading2 ##\n\n### Heading3 ###\n\n`

I really like this library much better than the others, but this is causing some problems.  I'll start looking at the code to try to figure it out, but not sure if anyone else has encountered this and if it can be solved easily.

Thanks!

**Comment by ankitsinghania94** [comment]
+1

**Comment by CharlesMangwa** [comment]
Hi @robinschaaf! I'm so sorry for this late reply, I've been so busy this last couple of weeks 😣…

You're completely right: even if I'm used to this `\n\n` syntax, RNSM should also handle the `\n` case. If I'm not mistaken, the problem probably comes from either the `text` rule [in rules.js](https://github.com/CharlesMangwa/react-native-simple-markdown/blob/master/rules.js) (I'm not completyly satisfied with it anymore, I will probably rewrite the whole thing anytime soon 🤔…) or the [MD parser itself](https://github.com/CharlesMangwa/simple-markdown).

If you can figure it out and send a PR it would be so much appreciated 🎉!
