### ISSUE TITLE
Does Link working?

### ISSUE THREAD

**Issue by linonetwo** [CharlesMangwa/react-native-simple-markdown#3]
```
          <Markdown styles={markDownStyle}>
            #Try writing a link!
            {'\n\n'}
            [baidu](www.baidu.com/)  
              CLick it!
          </Markdown>
```
Seems it is not clickable?

**Comment by CharlesMangwa** [comment]
Hi! As mentioned in the readme file: link is still WIP by now ([see here](https://github.com/CharlesMangwa/react-native-simple-markdown#wip)). I've been quite busy these last couple of days, and didn't had the time to work on this RNSM. However I have an idea on how to solve this issue but feel free to leave a PR if you do to!

**Comment by linonetwo** [comment]
OK, I'm glad to PR for link feature next week.

But image seems not working currently... Long way to go
```
          <Markdown styles={markDownStyle}>
            Some *really* basic **Markdown**.
            {'\n\n'}
            ![loli](http://img1.gtimg.com/comic/pics/hv1/171/204/2021/131467716.jpg)
          </Markdown>
```

**Comment by linonetwo** [comment]
Can you share your idea about Link ?

there is [a package](https://github.com/exponentjs/react-native-link/blob/master/link.js) but package it use is probably ios only.

**Comment by CharlesMangwa** [comment]
Well: I didn't encounter major issue with Image, did you try with an https link as well?

**Comment by CharlesMangwa** [comment]
It's a pretty simple idea actually: wrap the link text into a `<Text />` component and put it into a `<TouchableWithouthFeedback />` with the link URL in the `onPress` prop. 
If this works, we should be able to stylize the link (by passing style for the `<Text />` component) and link will work on both iOS & Android (thanks to `<TouchableWithouthFeedback />`).
It's just that I don't have enough time to try this at the moment.

**Comment by linonetwo** [comment]
Https image crashes my app too, it will show up 'Unfortunately, APP has stopped'
```
          <Markdown styles={markDownStyle}>
            Some *really* basic **Markdown**.
            {'\n\n'}
            ![loli](https://upload.wikimedia.org/wikipedia/commons/thumb/8/89/Lolicon_Sample.png/1280px-Lolicon_Sample.png?1473001947598)
          </Markdown>
```

**Comment by CharlesMangwa** [comment]
Oh that's awkward… I just ran your code and didn't encountered any issue or crash. Maybe your problem is somewhere else 😕 ?
<img width="432" alt="screenshot 2016-09-04 a 17 25 00" src="https://cloud.githubusercontent.com/assets/8975443/18231907/b83df6a8-72c4-11e6-873a-bcc1e8655a3c.png">

**Comment by linonetwo** [comment]
I'll try to figure it out, maybe it's due to Animation...

Thanks

**Comment by linonetwo** [comment]
Now Link will pop up the native browser on a press.

I tried TouchableOpacity, but it will warning about 'unexpected view type nested under text node'. Can't figure out why so I use Text node with onPress directly. I think the difference between them is little: TouchableOpacity will become transparent when touched, Text doesn't.

 If you care about this, I will spend more time on it trying to figure out, or I will working on more markdowns...

BTW: what's the difference between Autolink and Link?

**Comment by CharlesMangwa** [comment]
Hey! I'll check out your PR, thanks again !

`Link` is a normal link as you'd write it in MD whereas `Autolink` will parse your content and automatically generate a clickable element if you've just written : `http://www.github.com/` for instance.

**Comment by CharlesMangwa** [comment]
Closing issue #3
