### ISSUE TITLE
[Question] Why forking `simple-markdown`?

### ISSUE THREAD

**Issue by alvaromb** [CharlesMangwa/react-native-simple-markdown#31]
I'm curious, I've just read the `package.json` file and I found out that you have forked `simple-markdown`, can I ask you why?

Shouldn't the library use the original project as a dependency?

I'm open to send PRs if you need a hand.

**Comment by CharlesMangwa** [comment]
Hi @alvaromb! I've forked it because `simple-markdown` had some unnecessary devDependencies and it's wasn't maintained anymore!
