### ISSUE TITLE
Links give errors

### ISSUE THREAD

**Issue by ErkanSensei** [CharlesMangwa/react-native-simple-markdown#36]
Whenever I use a link, I either get ``Cannot read property 'react' of undefined`` when the debugger is on, or I get ``undefined is not an object(evaluating 'rules[ast.type][property]')`` when the debugger is off. This is happening with simple links, such as the ones found on http://www.markitdown.net/markdown

**Comment by CharlesMangwa** [comment]
Hi @ErkanSensei! Do you have this issue with the NPM package or the version from this repo's `master`?

**Comment by ErkanSensei** [comment]
NPM

**Comment by prijindal** [comment]
Facing same issue
Installed from npm

**Comment by kohei-takata** [comment]
I changed my `package.json` like this, and `undefined is not an object(evaluating 'rules[ast.type][property]')` does not happen.
```
"dependencies": {
   ...
    "react-native-simple-markdown": "git://github.com/CharlesMangwa/react-native-simple-markdown.git"
  }
```

**Comment by christophrowley** [comment]
Any updates on this? It's be great if the fix could be published to NPM. Not exactly sure why that hasn't happened yet...

**Comment by Plsr** [comment]
Looks like this issue was resolved with the most recent publish to npm, which makes sense since the issue itself seems to be fixed for some time now and all that was missing was a new release on npm.
Just upgraded to `1.1.0` in a project and the error was gone with the update.

**Comment by CharlesMangwa** [comment]
Thanks for letting us know! Closing this issue then.
