### ISSUE TITLE
Blockquotes produce error on Android

### ISSUE THREAD

**Issue by nathan-k** [CharlesMangwa/react-native-simple-markdown#38]
Installing from the git repo and using blockquotes on Android produces this error:

`Nesting of <View> withing <Text> is not supported on Android.`

**Comment by CharlesMangwa** [comment]
Hi @nathan-k! Do you have the same problem with the NPM package?

**Comment by terrysahaidak** [comment]
@CharlesMangwa I've just tested it and where is no such problem in npm package.

**Comment by terrysahaidak** [comment]
It seems like the problem is [here](https://github.com/CharlesMangwa/react-native-simple-markdown/blob/master/rules.js#L24). If we replace `Text` by `View` it works well, I can submit a PR to fix that.

**Comment by CharlesMangwa** [comment]
I think I've already face this issue because it triggers an error on Android if I remember well. But if you can test the different cases of blockquotes (plain text, extract from an array/object, etc) and submit a PR, that would be 💯

**Comment by afilp** [comment]
Similar case unfortunately with lists:

https://github.com/CharlesMangwa/react-native-simple-markdown/issues/90

**Comment by diolar** [comment]
The issue with the `list` is that when the markdown file is parsed, the content of the list items is being wrapped inside `p` tags and that forces the list item to replace it with a `View`. 
I order to avoid that i replaced the paragraph Views with Text.
A bit of styling for the list and everything looks as it should.
```
const markdownStyles = {
   listItem: {
      position: 'relative',
      paddingLeft: 24,
  },
   listItemBullet: {
      position: 'absolute',
      left: 8,
      top: 0,
  },
}

  <Markdown
    styles={markdownStyles}
    rules={{
      paragraph: {
        react: (node, output, state) => (
          <Text key={state.key}>
            {output(node.content, state)}
          </Text>
        ),
      },
    }}
  >
    {content}
  </Markdown>

```

Where `<Text />` is a styled Text component in my case but it could as easily be a native Text with a style object.
