### ISSUE TITLE
Code produces an error while parsing

### ISSUE THREAD

**Issue by terrysahaidak** [CharlesMangwa/react-native-simple-markdown#39]
Just trying to parse inline code snippet like
```
`code`
```
but it produces an error:
![image](https://cloud.githubusercontent.com/assets/7809008/25037800/64b3c0b8-20fb-11e7-9036-f892d5dd223b.png)

**Comment by CharlesMangwa** [comment]
Hi @terrysahaidak! Sorry for the inconvenience, I did have too much time to work on RNSM lately. If you could send a PR that would be awesome!

**Comment by terrysahaidak** [comment]
Just tried with the brand new app and package from github and it works as expected. I will test again with my another project where it had not worked.

**Comment by terrysahaidak** [comment]
Where is no problem with package from github, so I can close this, thank you @CharlesMangwa.
