### ISSUE TITLE
Code blocks should be blocks with horizontal scroll

### ISSUE THREAD

**Issue by terrysahaidak** [CharlesMangwa/react-native-simple-markdown#41]
I've noticed that code blocks render into black view in github package and into inline code blocks in npm package.

So I've played with it and have created a view which renders it without text-wrap into horizontal scroll view.

![image](https://cloud.githubusercontent.com/assets/7809008/25043503/d335598c-2120-11e7-9980-3863f0753b5e.png)

Just want to ask if it really needed for that lib? Because for my case it must have (Gitter mobile client).

**Comment by CharlesMangwa** [comment]
Yeah of course! That would be awesome: just send a PR @terrysahaidak!
