### ISSUE TITLE
How are list items styled? 

### ISSUE THREAD

**Issue by jcollum** [CharlesMangwa/react-native-simple-markdown#42]
Code: 

```
  <Markdown
        style={{
          listItemBullet: { color: '#ed79db' },
          listItemText: { color: '#de6262' }
        }}>
        ###I am a list:{'\n\n\n'}
        - This is my first item{'\n\n'}
        - This is my second item{'\n\n'}
        - This is my third item{'\n\n'}
      </Markdown>
```

Result: 

<img width="369" alt="greenshot 2017-04-20 09 31 52" src="https://cloud.githubusercontent.com/assets/704514/25241823/40be8354-25ac-11e7-868f-73a9f54a6c35.png">

Clearly I need to fix those bullets. 

Seems like the list style is not propagating correctly. Or I'm passing the wrong thing. Tried passing `list:{...}` as well with no luck.

**Comment by jcollum** [comment]
Solved it. 

You are using a prop called `styles` while the base react elements use `style`:

```
class ViewColoredBoxesWithText extends Component {
  render() {
    return (
      <View style={{flexDirection: 'row', height: 100, padding: 20}}>
        <View style={{backgroundColor: 'blue', flex: 0.3}} />
        <View style={{backgroundColor: 'red', flex: 0.5}} />
        <Text>Hello World!</Text>
      </View>
    );
  }
}
```

https://facebook.github.io/react-native/docs/view.html

It's a small problem but as an end-user I'd really prefer you use the same property names as the React-Native library.

**Comment by benvium** [comment]
The `styles` property is passing down a collection of style objects (fields listItemBullet, listItemText etc) whereas the React Native `style` property is a single style object (fields backgroundColor, width etc), so they are different.

**Comment by jcollum** [comment]
That's not correct. 

>The style prop can be a plain old JavaScript object. That's the simplest and what we usually use for example code. **You can also pass an array of styles** - the last style in the array has precedence, so you can use this to inherit styles.

https://facebook.github.io/react-native/docs/style.html

**Comment by benvium** [comment]
You're right that you can pass an array of to the RN `style` prop. They're 'merged' together to produce a single resulting style - we use this feature a lot.
This is different to passing in a object, where each key maps to a style object. This is what the `styles` prop in markdown is doing.

**Comment by jcollum** [comment]
Ah that clears it up, so I'd need to merge the styles before passing to RNSM.

**Comment by CharlesMangwa** [comment]
As explained by @benvium, here you'll need to use the `styles` prop, as shown in the 1st example of the README :)

**Comment by appjitsu** [comment]
@jcollum How did you fix your bullet points styling? I have the same issue.
