### ISSUE TITLE
White listing 'hr' does not render it correctly

### ISSUE THREAD

**Issue by sunkibaek** [CharlesMangwa/react-native-simple-markdown#43]
While below renders as expected:

```
        <Markdown
          styles={{ text: textStyle }}
        >
          hello{'\n'}
          ---{'\n'}
          world
        </Markdown>
```

putting 'hr' in whitelist does not parse --- into hr

```
        <Markdown
          styles={{ text: textStyle }}
          whitelist={['hr']}
        >
          hello{'\n'}
          ---{'\n'}
          world
        </Markdown>
```

Seems like I am missing something obvious -- any advice?

**Comment by CharlesMangwa** [comment]
The whitelist/blacklist feature is just here to specify if you want to use the default style or not, as explained [here](https://github.com/CharlesMangwa/react-native-simple-markdown#rules) :)
