### ISSUE TITLE
No component found for view with name RCTVirtualText

### ISSUE THREAD

**Issue by sunkibaek** [CharlesMangwa/react-native-simple-markdown#48]
Since I have upgraded to ReactNative 0.44.0 , I am getting following error:

<img width="376" alt="2017-05-12 2 38 31" src="https://cloud.githubusercontent.com/assets/1668601/25986795/52bd114c-372c-11e7-9630-b76d8d3965a9.png">

Any ideas how to go about it? Thanks!

**Comment by sunkibaek** [comment]
Seems to be related to: https://github.com/facebook/react-native/issues/13925

**Comment by CharlesMangwa** [comment]
Hi! This seems to be a RN-related error, but feel free to re-open this issue if needed.
