### ISSUE TITLE
Using dashes for lists doesn't work

### ISSUE THREAD

**Issue by danieljvdm** [CharlesMangwa/react-native-simple-markdown#5]
The following markdown:

```
- Item 1
- Item 2
- Item 3
```
doesn't render using this library.

**Comment by danieljvdm** [comment]
On further inspection, it is converting the dashes to bullets, but it's not creating new lines or wrapping text.

**Comment by CharlesMangwa** [comment]
Hi @danieljvdm, thanks for the feedback! If you can fix it and send a PR that would be awesome. Otherwise I'll take a couple of minutes this week-end to solve this issue.

**Comment by danieljvdm** [comment]
Hey, I just came back to this and seems that the intended behavior still doesn't work. Was this meant to be fixed when you closed the issue or should I look into doing a PR?

**Comment by CharlesMangwa** [comment]
Hey @danieljvdm! If you still have your issue, don't hesitate to send a PR, you'd be nice to you yeah!
