### ISSUE TITLE
View nested within a <Text> must ave width and height

### ISSUE THREAD

**Issue by pietro909** [CharlesMangwa/react-native-simple-markdown#52]
Hi,
I get this problem with my Markdown file.

Please note that with the sample in the Readme in works.

<img width="375" alt="screen shot 2017-06-11 at 23 10 15" src="https://user-images.githubusercontent.com/2094604/27014581-e24008e2-4efb-11e7-9fa5-e54f87c3113e.png">

**Comment by aaronleo28** [comment]
What was the markdown text causing this bug?

**Comment by pietro909** [comment]
Here's a sample text (same structure, I just invented a language due to NDA):

https://pastebin.com/eu6pUi6k

At the moment I solved it using [react-native-easy-markdown](https://www.npmjs.com/package/react-native-easy-markdown).

**Comment by CharlesMangwa** [comment]
Hi! This should be fixed at the same time as #60
