### ISSUE TITLE
blockQuoteText color doesn't work

### ISSUE THREAD

**Issue by jacobjuul** [CharlesMangwa/react-native-simple-markdown#54]
No matter what I do, `blockQuoteText` takes on the color of whatever is set in the `text` style.

**Comment by kid-wumeng** [comment]
+1

**Comment by Zeikko** [comment]
I seem to experience similar issues with `link`

**Comment by CharlesMangwa** [comment]
IIRC this have never been implemented for these 2 elements. Feel free to join the discussion [here](#75), if you'd like to see some features make it through to the v2!
