### ISSUE TITLE
Is there a reason why this module uses a fork as a dependency?

### ISSUE THREAD

**Issue by hugo-marques-m3** [CharlesMangwa/react-native-simple-markdown#58]
From `package.json`
```
"dependencies": {
    "lodash": "^4.15.0",
    "simple-markdown": "git://github.com/CharlesMangwa/simple-markdown.git"
  },
```
simple-markdown is a fork of `https://github.com/Khan/simple-markdown`

Is there a reason for this?

**Comment by CharlesMangwa** [comment]
The reason is that simple-markdown use to have a few errors fixed by the fork :)
