### ISSUE TITLE
Why does new line not work now?

### ISSUE THREAD

**Issue by linonetwo** [CharlesMangwa/react-native-simple-markdown#7]
I'm curious about it, I may make a PR for this. But I am not clear about where to start.

**Comment by CharlesMangwa** [comment]
Hi @linonetwo! Do you still have this problem?

**Comment by CharlesMangwa** [comment]
Closing issue #07

**Comment by linonetwo** [comment]
Sorry for being brief, what I concerned is the consistency between traditional MD and this.

Since my crawler crawls lots of MD from GitHub or so, they don't have ```{'\n'}``` but instead two space after each line.

**Comment by CharlesMangwa** [comment]
Can you show me an example of your issue please? Because 2 spaces line breaking do work actually.

**Comment by linonetwo** [comment]
Oh, I hadn't tried it yet, since in Readme.MD you use ```{'\n'}``` , which is unusual, so I misunderstood it as we can only use this.

If it's ok to just use two spaces, then this issue can be safely close...

**Comment by linonetwo** [comment]
And ```newline (<Text>)``` is still  WIP  on Readme.MD

**Comment by CharlesMangwa** [comment]
Yes you're right, I forgot to remove it. But yeah: it takes the 2 spaces 🙂

**Comment by CharlesMangwa** [comment]
Closing issue #07

**Comment by dinodsaurus** [comment]
Im still having some issues with new lines, I copy pasted your example and this is how it looks like - https://www.dropbox.com/s/ey143aw603z4ysm/Screenshot%202016-12-19%2016.59.42.png?dl=0

**Comment by CharlesMangwa** [comment]
Hi @dinodsaurus! I don't have any new lines in my example. Did you try ton add `\n`?

**Comment by dinodsaurus** [comment]
First of all thanks for this quick response! :)
If I add `\n`it makes a line break but it doesnt render headings anymore, do I need to add `flex: 1`to all text elements ?
I add `/n`after `h1` - 
https://www.dropbox.com/s/fj67bmeg8bbsb1z/Screenshot%202016-12-19%2017.12.44.png?dl=0

**Comment by CharlesMangwa** [comment]
Did you try with `{'\n\n'}` instead of `{'\n'}`? It should be better if I'm not mistaken

**Comment by dinodsaurus** [comment]
Thanks a lot! Sorry for this question, but didnt get it what you meant by `two spaces` in previous comments ;)
