### ISSUE TITLE
Long MarkDown is not displayed

### ISSUE THREAD

**Issue by Waltari10** [CharlesMangwa/react-native-simple-markdown#70]
When I use a really long markdown text it doesn't show up at all. It seems that the text is invisible as it still taking a lot of space and I can scroll the view that I've put it into.

**Comment by CharlesMangwa** [comment]
Hum that's weird indeed 🤔 … When you say "really long markdown" what do you mean?

**Comment by Waltari10** [comment]
The document is 8,906 words and 55,819 characters. It turned out that react-native itself is unable to show much this many words in a single Text component. I'm not sure what the threshold for amount of words or characters is. We ended up using a webview to display the document in HTML form instead.

**Comment by CharlesMangwa** [comment]
OK thanks for the input! That could be interesting to handle in the v2 👍
