### ISSUE TITLE
Doesn't work if the project doesn't use flow

### ISSUE THREAD

**Issue by emirotin** [CharlesMangwa/react-native-simple-markdown#71]
The version published to NPM uses flow-specific syntax (namely, type declaration).
This breaks imports for the projects that don't use flow.

**Comment by CharlesMangwa** [comment]
That's not really convenient indeed. This should be fixed in v1.1 by adding [this Babel plugin](https://babeljs.io/docs/plugins/transform-flow-strip-types/) 🙂

**Comment by CharlesMangwa** [comment]
This has been fixed in next branch [here](8c8242323bb272abed03728f37dec6916d00eb5b). Coming to you in the incoming `v2` =)
