### ISSUE TITLE
Hello 👋

### ISSUE THREAD

**Issue by sospedra** [CharlesMangwa/react-native-simple-markdown#72]
Is anyone mantaining this? 👀

**Comment by nielskrijger** [comment]
Not sure. Doesn't look like it.

@CharlesMangwa can you let us know what your current position is towards this library? If you've lost interest or are too busy to maintain, could you post an update in the README and/or request for a maintainer who wants to check & test PR's?

**Comment by nielskrijger** [comment]
I sent the maintainer an email a couple of days ago but haven't received a reply yet. 

Last release on NPM is quite a long time ago, I guess it's safe to assume this library is no longer being maintained 😞 

The warnings generate in RN 0.49 are driving me crazy (https://github.com/CharlesMangwa/react-native-simple-markdown/pull/66) so I had been looking for a fork published on npm. Didn't find one yet, lots of forks though. Looked at alternative libraries but they too appear to be ill-maintained; and switching might cause all sorts of bugs.

If someone knows of a good alternative, or is interested in setting one up please let me know.

**Comment by jackkinsella** [comment]
The warnings suck alright. The only way to make the library usable again is to temporarily disable the yellow box with `console.disableYellowBox = true`.

**Comment by nielskrijger** [comment]
Thanks @jackkinsella 

I did it as follows:

```javascript
/* eslint-disable no-console */
import React, { Component } from 'react';

/**
 * This HOC disables the yellow box warnings for wrapped component while
 * it is being rendered.
 *
 * This should only be used as a temporary measure, but can be useful
 * if wrapped component is not under your control.
 *
 * We don't have to concern ourselves with the original disableYellowBox
 * value. The entire yellow box setup is not loaded when using
 * NODE_ENV=production (a default for release configuration).
 */
function disableYellowBox(WrappedComponent) {
  class DisableYellowBox extends Component {
    componentWillMount() {
      console.disableYellowBox = true;
    }

    componentDidMount() {
      console.disableYellowBox = false;
    }

    componentWillUpdate() {
      console.disableYellowBox = true;
    }

    componentDidUpdate() {
      console.disableYellowBox = false;
    }

    render() {
      return <WrappedComponent {...this.props} {...this.state} />;
    }
  }

  return DisableYellowBox;
}

export default disableYellowBox;
```

And in Markdown component:

```javascript
// Disable yellow box because of this issue:
// https://github.com/CharlesMangwa/react-native-simple-markdown/pull/66
export default disableYellowBox(Markdown);
```

Not a permanent solution. Just waiting for a released for of this library now (there are plenty of forks, just no released ones yet afaik).

**Comment by jackkinsella** [comment]
@nielskrijger I like that approach a ton—it's elegant, encapsulated.

**Comment by stigi** [comment]
https://twitter.com/Charles_Mangwa/status/934034865623879681
> Hey! I’m planning a major rewrite for the v2 (from the ground up basically). I’ll take some time to post an issue discussing the future of the lib and publish the v1.1 on npm this week-end.

That was a while ago. I pinged him about some PRs especially #66 via DM. 🤞
A `v1.1` or even `v1.0.61` some of the PRs that accumulated would be a reason to celebrate 🎉

**Comment by CharlesMangwa** [comment]
Sorry for the (long) absence everyone! I've opened a discussion about the future of RNSM:[ join us](#75) if you have some ideas to share!
