### ISSUE TITLE
Image not displaying...

### ISSUE THREAD

**Issue by mattclevyr** [CharlesMangwa/react-native-simple-markdown#74]
If you can see the image in a browser window, but nothing displaying in your app, what should we look to? I am hoping that this is not an actual bug, but just my own error.

**Comment by Peretus** [comment]
You might make sure that the source for your image is HTTPS.

For example, the image source in the markdown should be HTTPS like this:

```
<Markdown styles={markdownStyles}>
  ![alt text](https://[SECURE-IMAGE-PATH].png)
</Markdown>
```
Versus the following insecure version: 

```
<Markdown styles={markdownStyles}>
  ![alt text](http://[INSECURE-IMAGE-PATH].png)
</Markdown>
```

Apple requires that images are loaded via HTTPS for them to display; if your image source URL is HTTP, it will not.

**Comment by CharlesMangwa** [comment]
@Peretus got it right imho. Feel free to test it by using the same URL in a normal `<Image />` component, hence that will mean that this issue isn't related with the lib :)
