### ISSUE TITLE
Warning with RN 0.51

### ISSUE THREAD

**Issue by rauliyohmc** [CharlesMangwa/react-native-simple-markdown#77]
```
Warning: Each child in an array or iterator should have a unique "key" prop. See https://fb.me/react-warning-keys for more information.
    in RCTVirtualText (at Text.js:555)
    in Text (created by Markdown)
    in RCTText (at Text.js:557)
    in Text (created by Markdown)
```

**Comment by mmmurf** [comment]
+1

**Comment by MatthieuLemoine** [comment]
Fixed in #66 but has not been released yet.

**Comment by CharlesMangwa** [comment]
Fixed in `v1.1.0` 👍

**Comment by rgommezz** [comment]
Using `v1.1.0` I am having the below issue, so I had to resort back:

![image](https://user-images.githubusercontent.com/4982414/35105365-c8e30c96-fc6b-11e7-897d-e32f820ed4fa.png)

**Comment by CharlesMangwa** [comment]
Could you tell me which rule generates this error?

**Comment by rgommezz** [comment]
I am not passing any rules, just some `styles`. But even removing the `styles` I get the error

**Comment by CharlesMangwa** [comment]
Could you send me a copy of the .md you're rendering or your .md content hierarchy?

**Comment by arma7x** [comment]
using 1.1.0, but rules.js in package.tgz still not update to latest version.
