### ISSUE TITLE
React-Native & React-Navigation - Markdown Links?

### ISSUE THREAD

**Issue by appjitsu** [CharlesMangwa/react-native-simple-markdown#78]
I have an Expo React-Native app that uses React-Navigation.

Does this component allow me to generate links where I can insert code to call React-Navigation? Our use case is going from a Terms and Conditions screen to the Privacy Policy screen; both of which use markdown.

**Comment by CharlesMangwa** [comment]
At this time, RNSM only allows you to open HTTP URLs. You could use another library to parse your content and render a touchable element redirecting to your other page?

**Comment by appjitsu** [comment]
You got any recommendations for that?

**Comment by CharlesMangwa** [comment]
Try something like react-native-parsed-text, I think it may suit your use case.

**Comment by appjitsu** [comment]
Ok thanks.

~ Jason

**Comment by CharlesMangwa** [comment]
Sure thing.
