### ISSUE TITLE
1.0.60rc2 => 1.1.0 layout issue

### ISSUE THREAD

**Issue by todorone** [CharlesMangwa/react-native-simple-markdown#80]
Hi @CharlesMangwa ,
Thanks a lot for Your hard work on this great library.

When upgrading from `1.0.60rc2` to `1.1.0` I have this issue, that completely breaks text layout. Can You please investigate what could be the problem? Thanks.
 
![screenshot 2018-01-24 15 42 22](https://user-images.githubusercontent.com/423701/35335174-715fda06-011d-11e8-806e-e20de12dfdcc.png)
![screenshot 2018-01-24 15 40 34](https://user-images.githubusercontent.com/423701/35335179-73f17fea-011d-11e8-8a14-6eb98724fa58.png)

**Comment by CharlesMangwa** [comment]
Hi @todorone! Could you try to reproduce your MD & styles here to help the debug process pls: https://snack.expo.io/By2dzl04G?

**Comment by todorone** [comment]
@CharlesMangwa Thanks for prompt reply.
Adding `paragraph: {},` to styles cause the mess. Please suggest what should I use to style paragraphs of text?

**Comment by CharlesMangwa** [comment]
Here is the default style for `paragraph`:

```js
paragraph: {
  flexWrap: 'wrap',
  flexDirection: 'row',
  alignItems: 'flex-start',
  justifyContent: 'flex-start',
}
```

If you passed an empty object, that would simply override this. So try to give your paragraph the full width (minus padding) of its 100%-width parent, plus all useful styles.

But that’s just my 2 cents, it would be easier to help you with a Snack example.

**Comment by todorone** [comment]
@CharlesMangwa Yes, if I looked to sources of the new version, I'd understand what's the problem. Now it makes the sense how to customize `paragraph` style, but I'd advise to include it somewhere in docs/faq that `paragraph` style should maintain `flexDirection: 'row'` to be displayed correctly for those who'll face the same issue.
Thanks!

**Comment by CharlesMangwa** [comment]
Sure thing!
