### ISSUE TITLE
Markdown content breaks to new lines in every space

### ISSUE THREAD

**Issue by afilp** [CharlesMangwa/react-native-simple-markdown#81]
Please see the image:

![image](https://user-images.githubusercontent.com/7850073/35461406-840e2386-02f0-11e8-9a87-63216ed90cab.png)

This markdown content was working fine for many months (it was rendered in the entire width of the screen, now you see that it breaks to a new line in every space). 

I am not sure what causes this, could it be the latest React native or other latest packages?

I am using the latest released npm package:

``    "react-native-simple-markdown": "^1.1.0",``

**Comment by CharlesMangwa** [comment]
Hi @afilp! Did you check if your issue was related to #80?

**Comment by afilp** [comment]
@CharlesMangwa Indeed, that was the case. Thanks!

**Comment by CharlesMangwa** [comment]
Glad it helped!
