### ISSUE TITLE
Line Breaks

### ISSUE THREAD

**Issue by bernatfortet** [CharlesMangwa/react-native-simple-markdown#9]
Hello! I'm trying to render Markdown from a prop
```js
<Markdown>{this.prop.content}</Markdown>
```

The content is like this:
```md
# This is my title
## Subtitle

Some text here

1. Item 1
2. Item 2
```
I see that you specify line breaks ` {'\n\n'}`
What would you suggest to not have to add manually all those line breaks?

Thanks! This module is fantastic!

**Comment by CharlesMangwa** [comment]
Hi @bernatfortet! Thanks a lot ^^! Well I wrote `{'n\n'}` to show that there were line breaks there. However you just have to hit `Enter` twice in the text contained in `this.props.content` to add your line break. Tell me if it helps!

**Comment by CharlesMangwa** [comment]
Closing issue #09

**Comment by bernatfortet** [comment]
Thanks! This helped! (I'm just getting used to the notification system, sorry for the delay)

**Comment by bernatfortet** [comment]
I'm just revisiting my markdown implementation but when I try to remove the n lines it's not working, here's an example:

**With {'\n\n'}**

<img width="321" alt="screen shot 2016-12-25 at 1 16 46 pm" src="https://cloud.githubusercontent.com/assets/390010/21471096/a8e55dbc-caa4-11e6-868f-3b098293db6d.png">

```md
<Markdown styles={markdownStyles} rules={rules}>

  #Markdown in react-native is so cool! {'\n\n'}

  You can **emphasize** what you want, or just _suggest it_ 😏…{'\n'}

  You can even [**link your website**](http://charlesmangwa.surge.sh) or if you prefer: [email somebody](mailto:email@somebody.com){'\n'}

  Spice it up with some GIFs 💃:

  ![Some GIF](https://media.giphy.com/media/dkGhBWE3SyzXW/giphy.gif){'\n'}

  And even add a cool video 😎!{'\n'}

  [![A cool video from YT](https://img.youtube.com/vi/dQw4w9WgXcQ/0.jpg)](http://www.youtube.com/watch?v=dQw4w9WgXcQ)

  [![Another one from Vimeo](https://i.vimeocdn.com/video/399486266_640.jpg)](https://vimeo.com/57580368)
</Markdown>
```

**Without {'\n\n'}**
<img width="320" alt="screen shot 2016-12-25 at 1 18 31 pm" src="https://cloud.githubusercontent.com/assets/390010/21471095/a7c5ea96-caa4-11e6-93b8-f3d6eacea7d9.png">

```md
<Markdown styles={markdownStyles} rules={rules}>

  #Markdown in react-native is so cool!

  You can **emphasize** what you want, or just _suggest it_ 😏…

  You can even [**link your website**](http://charlesmangwa.surge.sh) or if you prefer: [email somebody](mailto:email@somebody.com)

  Spice it up with some GIFs 💃:

  ![Some GIF](https://media.giphy.com/media/dkGhBWE3SyzXW/giphy.gif)

  And even add a cool video 😎!

  [![A cool video from YT](https://img.youtube.com/vi/dQw4w9WgXcQ/0.jpg)](http://www.youtube.com/watch?v=dQw4w9WgXcQ)

  [![Another one from Vimeo](https://i.vimeocdn.com/video/399486266_640.jpg)](https://vimeo.com/57580368)
</Markdown>
```

**Comment by pa3** [comment]
@bernatfortet I believe that is because of how compiling JSX to JS works. 

When you do something like:
```
<A>
  line1
  line2
</A>
```
It will be compiled (by babel) to the following JS code: `React.createElement(A, null, 'line1 line2')`. 

But when you write it like this:
```
<A>
  line1 {'\n'}
  line2
</A>
```
You'll get `React.createElement(A, null, 'line1 ', '\n', 'line2')` as a result.

If you'll pass a variable containing text with line-breaks as <Markdown> child:
```
<Mardown>{yourVarWithLineBreaks}</Markdown>
```
it will work as expected.

In case you want to show hard-coded text, place your line-breaks explicitly.
